import type { RootEntry } from "./types";

export const ROOTS: RootEntry[] = [
  {
    id: "ktb",
    letters: ["ك", "ت", "ب"],
    gloss: "write",
    weakness: "sound",
    formIBab: "nasara",
    forms: [1, 2, 3, 4, 6, 8, 10],
  },
  {
    id: "nSr",
    letters: ["ن", "ص", "ر"],
    gloss: "help",
    weakness: "sound",
    formIBab: "nasara",
    forms: [1, 3, 8, 10],
  },
  {
    id: "xrj",
    letters: ["خ", "ر", "ج"],
    gloss: "go out",
    weakness: "sound",
    formIBab: "nasara",
    forms: [1, 2, 4, 6, 10],
  },
  {
    id: "drs",
    letters: ["د", "ر", "س"],
    gloss: "study",
    weakness: "sound",
    formIBab: "nasara",
    forms: [1, 2, 3, 6],
  },
  {
    id: "Tlb",
    letters: ["ط", "ل", "ب"],
    gloss: "seek",
    weakness: "sound",
    formIBab: "nasara",
    forms: [1, 8],
  },
  {
    id: "tb3",
    letters: ["ت", "ب", "ع"],
    gloss: "follow",
    weakness: "sound",
    formIBab: "fariha",
    forms: [1, 8],
  },
  {
    id: "nZr",
    letters: ["ن", "ظ", "ر"],
    gloss: "look",
    weakness: "sound",
    formIBab: "nasara",
    forms: [1, 3, 8, 10],
  },
  {
    id: "Hml",
    letters: ["ح", "م", "ل"],
    gloss: "carry",
    weakness: "sound",
    formIBab: "daraba",
    forms: [1, 8],
  },
  {
    id: "Drb",
    letters: ["ض", "ر", "ب"],
    gloss: "hit",
    weakness: "sound",
    formIBab: "daraba",
    forms: [1],
  },
  {
    id: "jls",
    letters: ["ج", "ل", "س"],
    gloss: "sit",
    weakness: "sound",
    formIBab: "daraba",
    forms: [1],
  },
  {
    id: "rj3",
    letters: ["ر", "ج", "ع"],
    gloss: "return",
    weakness: "sound",
    formIBab: "daraba",
    forms: [1, 4, 10],
  },
  {
    id: "3rf",
    letters: ["ع", "ر", "ف"],
    gloss: "know",
    weakness: "sound",
    formIBab: "daraba",
    forms: [1, 2, 5, 10],
  },
  {
    id: "ftH",
    letters: ["ف", "ت", "ح"],
    gloss: "open",
    weakness: "sound",
    formIBab: "fataha",
    forms: [1, 7, 8],
  },
  {
    id: "dxl",
    letters: ["د", "خ", "ل"],
    gloss: "enter",
    weakness: "sound",
    formIBab: "fataha",
    forms: [1, 4, 10],
  },
  {
    id: "jm3",
    letters: ["ج", "م", "ع"],
    gloss: "gather",
    weakness: "sound",
    formIBab: "fataha",
    forms: [1, 2, 4, 8, 10],
  },
  {
    id: "qT3",
    letters: ["ق", "ط", "ع"],
    gloss: "cut",
    weakness: "sound",
    formIBab: "fataha",
    forms: [1, 2, 7, 8],
  },
  {
    id: "frH",
    letters: ["ف", "ر", "ح"],
    gloss: "be glad",
    weakness: "sound",
    formIBab: "fariha",
    forms: [1, 2, 10],
  },
  {
    id: "sm3",
    letters: ["س", "م", "ع"],
    gloss: "hear",
    weakness: "sound",
    formIBab: "fariha",
    forms: [1, 4, 8],
  },
  {
    id: "3lm",
    letters: ["ع", "ل", "م"],
    gloss: "know",
    weakness: "sound",
    formIBab: "fariha",
    forms: [1, 2, 4, 5, 10],
  },
  {
    id: "fhm",
    letters: ["ف", "ه", "م"],
    gloss: "understand",
    weakness: "sound",
    formIBab: "fariha",
    forms: [1, 2, 5],
  },
  {
    id: "Hfz",
    letters: ["ح", "ف", "ظ"],
    gloss: "memorize",
    weakness: "sound",
    formIBab: "fariha",
    forms: [1, 8, 10],
  },
  {
    id: "qbl",
    letters: ["ق", "ب", "ل"],
    gloss: "accept",
    weakness: "sound",
    formIBab: "fariha",
    forms: [1, 2, 4, 5, 10],
  },
  {
    id: "krm",
    letters: ["ك", "ر", "م"],
    gloss: "be noble",
    weakness: "sound",
    formIBab: "karuma",
    forms: [1, 2, 4, 5, 10],
  },
  {
    id: "Hsn",
    letters: ["ح", "س", "ن"],
    gloss: "be good",
    weakness: "sound",
    formIBab: "karuma",
    forms: [1, 2, 4, 10],
  },
  {
    id: "Hsb",
    letters: ["ح", "س", "ب"],
    gloss: "think / reckon",
    weakness: "sound",
    formIBab: "hasiba",
    forms: [1],
  },
  {
    id: "nzl",
    letters: ["ن", "ز", "ل"],
    gloss: "descend",
    weakness: "sound",
    formIBab: "daraba",
    forms: [1, 2, 4, 5, 10],
  },
  {
    id: "qdm",
    letters: ["ق", "د", "م"],
    gloss: "precede",
    weakness: "sound",
    formIBab: "nasara",
    forms: [1, 2, 4, 5, 10],
  },
  {
    id: "Hmr",
    letters: ["ح", "م", "ر"],
    gloss: "be red",
    weakness: "sound",
    formIBab: "fataha",
    forms: [9],
  },
  {
    id: "qwl",
    letters: ["ق", "و", "ل"],
    gloss: "say",
    weakness: "ajwaf",
    formIBab: "nasara",
    forms: [1, 2, 3, 4, 5, 6, 10],
  },
  {
    id: "by3",
    letters: ["ب", "ي", "ع"],
    gloss: "sell",
    weakness: "ajwaf",
    formIBab: "daraba",
    forms: [1, 2, 3, 4, 5, 10],
  },
  {
    id: "xwf",
    letters: ["خ", "و", "ف"],
    gloss: "fear",
    weakness: "ajwaf",
    formIBab: "fariha",
    forms: [1, 2, 4, 5, 10],
  },
  {
    id: "qwm",
    letters: ["ق", "و", "م"],
    gloss: "stand",
    weakness: "ajwaf",
    formIBab: "nasara",
    forms: [1, 2, 3, 4, 5, 6, 10],
  },
  {
    id: "syr",
    letters: ["س", "ي", "ر"],
    gloss: "travel / go",
    weakness: "ajwaf",
    formIBab: "daraba",
    forms: [1, 2, 3, 5, 6, 10],
  },
  {
    id: "zwr",
    letters: ["ز", "و", "ر"],
    gloss: "visit",
    weakness: "ajwaf",
    formIBab: "nasara",
    forms: [1, 2, 3, 5, 6, 10],
  },
  {
    id: "Tyr",
    letters: ["ط", "ي", "ر"],
    gloss: "fly",
    weakness: "ajwaf",
    formIBab: "daraba",
    forms: [1, 2, 4, 5, 6, 10],
  },
  {
    id: "nwm",
    letters: ["ن", "و", "م"],
    gloss: "sleep",
    weakness: "ajwaf",
    formIBab: "fataha",
    forms: [1, 2, 4, 5, 10],
  },
  {
    id: "w3d",
    letters: ["و", "ع", "د"],
    gloss: "promise",
    weakness: "mithal",
    formIBab: "daraba",
    forms: [1, 2, 3, 4, 5, 6, 8, 10],
  },
  {
    id: "wjd",
    letters: ["و", "ج", "د"],
    gloss: "find",
    weakness: "mithal",
    formIBab: "daraba",
    forms: [1, 4, 5, 6, 10],
  },
  {
    id: "wSl",
    letters: ["و", "ص", "ل"],
    gloss: "arrive / connect",
    weakness: "mithal",
    formIBab: "daraba",
    forms: [1, 2, 3, 4, 5, 6, 8, 10],
  },
  {
    id: "wq3",
    letters: ["و", "ق", "ع"],
    gloss: "fall / happen",
    weakness: "mithal",
    formIBab: "daraba",
    forms: [1, 2, 4, 5, 8, 10],
  },
  {
    id: "wD3",
    letters: ["و", "ض", "ع"],
    gloss: "put / place",
    weakness: "mithal",
    formIBab: "fataha",
    forms: [1, 2, 4, 5, 8, 10],
  },
  {
    id: "wld",
    letters: ["و", "ل", "د"],
    gloss: "give birth",
    weakness: "mithal",
    formIBab: "daraba",
    forms: [1, 2, 4, 5, 6, 10],
  },
  {
    id: "wqf",
    letters: ["و", "ق", "ف"],
    gloss: "stand / stop",
    weakness: "mithal",
    formIBab: "daraba",
    forms: [1, 2, 4, 5, 8, 10],
  },
  {
    id: "wSf",
    letters: ["و", "ص", "ف"],
    gloss: "describe",
    weakness: "mithal",
    formIBab: "daraba",
    forms: [1, 2, 5, 6, 8, 10],
  },
  {
    id: "d3w",
    letters: ["د", "ع", "و"],
    gloss: "call",
    weakness: "naqis",
    formIBab: "nasara",
    forms: [1, 3, 4, 5, 6, 8, 10],
  },
  {
    id: "rmy",
    letters: ["ر", "م", "ي"],
    gloss: "throw",
    weakness: "naqis",
    formIBab: "daraba",
    forms: [1, 3, 4, 5, 6, 8, 10],
  },
  {
    id: "mshy",
    letters: ["م", "ش", "ي"],
    gloss: "walk",
    weakness: "naqis",
    formIBab: "daraba",
    forms: [1, 2, 3, 4, 5, 6, 10],
  },
  {
    id: "bny",
    letters: ["ب", "ن", "ي"],
    gloss: "build",
    weakness: "naqis",
    formIBab: "daraba",
    forms: [1, 2, 3, 4, 5, 6, 10],
  },
  {
    id: "mdd",
    letters: ["م", "د", "د"],
    gloss: "extend",
    weakness: "mudaf",
    formIBab: "nasara",
    forms: [1, 2, 3, 5, 6, 8, 10],
  },
  {
    id: "rdd",
    letters: ["ر", "د", "د"],
    gloss: "return / reply",
    weakness: "mudaf",
    formIBab: "nasara",
    forms: [1, 2, 5, 8, 10],
  },
  {
    id: "Hbb",
    letters: ["ح", "ب", "ب"],
    gloss: "love",
    weakness: "mudaf",
    formIBab: "nasara",
    forms: [1, 2, 5, 6, 10],
  },
  {
    id: "shdd",
    letters: ["ش", "د", "د"],
    gloss: "tighten / intensify",
    weakness: "mudaf",
    formIBab: "nasara",
    forms: [1, 2, 5, 8, 10],
  },
  {
    id: "3dd",
    letters: ["ع", "د", "د"],
    gloss: "count",
    weakness: "mudaf",
    formIBab: "nasara",
    forms: [1, 2, 5, 8, 10],
  },
  {
    id: "axd",
    letters: ["أ", "خ", "ذ"],
    gloss: "take",
    weakness: "mahmuz_f",
    formIBab: "nasara",
    forms: [1, 8],
  },
  {
    id: "akl",
    letters: ["أ", "ك", "ل"],
    gloss: "eat",
    weakness: "mahmuz_f",
    formIBab: "nasara",
    forms: [1, 2, 5, 6, 10],
  },
  {
    id: "amr",
    letters: ["أ", "م", "ر"],
    gloss: "command",
    weakness: "mahmuz_f",
    formIBab: "nasara",
    forms: [1, 2, 5, 6, 10],
  },
  {
    id: "sAl",
    letters: ["س", "أ", "ل"],
    gloss: "ask",
    weakness: "mahmuz_a",
    formIBab: "fataha",
    forms: [1, 3, 5, 6, 10],
  },
  {
    id: "qrA",
    letters: ["ق", "ر", "أ"],
    gloss: "read",
    weakness: "mahmuz_l",
    formIBab: "fataha",
    forms: [1, 2, 4, 5, 6, 10],
  },
  {
    id: "bdA",
    letters: ["ب", "د", "أ"],
    gloss: "begin",
    weakness: "mahmuz_l",
    formIBab: "fataha",
    forms: [1, 2, 4, 5, 8, 10],
  },
];

export function rootArabic(entry: RootEntry): string {
  return entry.letters.join("");
}

export function getRoot(id: string): RootEntry {
  const found = ROOTS.find((root) => root.id === id);
  if (!found) throw new Error(`Unknown root ${id}`);
  return found;
}

export function soundRoots(): RootEntry[] {
  return ROOTS.filter((root) => root.weakness === "sound");
}

export function rootsByWeakness(type: RootEntry["weakness"]): RootEntry[] {
  return ROOTS.filter((root) => root.weakness === type);
}
